function [allData, scenario, sensors] = scene1()
%scene1 - Returns sensor detections
%    allData = scene1 returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = scene1 optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 23.2 (R2023b) and Automated Driving Toolbox 23.2 (R2023b).
% Generated on: 19-Nov-2023 21:23:13

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
[sensors, numSensors] = createSensors(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    objectDetections = {};
    laneDetections   = [];
    ptClouds = {};
    insMeas = {};
    isValidTime = false(1, numSensors);
    isValidLaneTime = false(1, numSensors);
    isValidPointCloudTime = false(1, numSensors);
    isValidINSTime = false(1, numSensors);

    % Generate detections for each sensor
    for sensorIndex = 1:numSensors
        sensor = sensors{sensorIndex};
        % Generate the ego vehicle lane boundaries
        if isa(sensor, 'visionDetectionGenerator')
            maxLaneDetectionRange = min(500,sensor.MaxRange);
            lanes = laneBoundaries(egoVehicle, 'XDistance', linspace(-maxLaneDetectionRange, maxLaneDetectionRange, 101));
        end
        type = getDetectorOutput(sensor);
        if strcmp(type, 'Objects only')
            if isa(sensor,'ultrasonicDetectionGenerator')
                [objectDets, isValidTime(sensorIndex)] = sensor(poses, time);
                numObjects = length(objectDets);
            else
                [objectDets, numObjects, isValidTime(sensorIndex)] = sensor(poses, time);
            end
            objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes only')
            [laneDets, ~, isValidTime(sensorIndex)] = sensor(lanes, time);
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes and objects')
            [objectDets, numObjects, isValidTime(sensorIndex), laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
            objectDetections = [objectDetections; objectDets(1:numObjects)]; %#ok<AGROW>
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'Lanes with occlusion')
            [laneDets, ~, isValidLaneTime(sensorIndex)] = sensor(poses, lanes, time);
            laneDetections   = [laneDetections laneDets]; %#ok<AGROW>
        elseif strcmp(type, 'PointCloud')
            if sensor.HasRoadsInputPort
                rdmesh = roadMesh(egoVehicle,min(500,sensor.MaxRange));
                [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor(poses, rdmesh, time);
            else
                [ptCloud, isValidPointCloudTime(sensorIndex)] = sensor(poses, time);
            end
            ptClouds = [ptClouds; ptCloud]; %#ok<AGROW>
        elseif strcmp(type, 'INSMeasurement')
            insMeasCurrent = sensor(actorState, time);
            insMeas = [insMeas; insMeasCurrent]; %#ok<AGROW>
            isValidINSTime(sensorIndex) = true;
        end
    end

    % Aggregate all detections into a structure for later use
    if any(isValidTime) || any(isValidLaneTime) || any(isValidPointCloudTime) || any(isValidINSTime)
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release all the sensor objects so they can be used again.
for sensorIndex = 1:numSensors
    release(sensors{sensorIndex});
end

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function [sensors, numSensors] = createSensors(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensors{1} = lidarPointCloudGenerator('SensorIndex', 1, ...
    'SensorLocation', [3.7 0], ...
    'MaxRange', 30, ...
    'AzimuthLimits', [-10 10], ...
    'ActorProfiles', profiles);
sensors{2} = visionDetectionGenerator('SensorIndex', 2, ...
    'SensorLocation', [0 0], ...
    'Yaw', -180, ...
    'MaxRange', 20, ...
    'DetectorOutput', 'Objects only', ...
    'Intrinsics', cameraIntrinsics([1814.81018227767 1814.81018227767],[320 240],[480 640]), ...
    'ActorProfiles', profiles);
sensors{3} = visionDetectionGenerator('SensorIndex', 3, ...
    'SensorLocation', [1.9 0], ...
    'MaxRange', 30, ...
    'DetectorOutput', 'Lanes and objects', ...
    'Intrinsics', cameraIntrinsics([1000 1000],[320 240],[480 640]), ...
    'ActorProfiles', profiles);
sensors{4} = lidarPointCloudGenerator('SensorIndex', 4, ...
    'SensorLocation', [2.8 -0.9], ...
    'Yaw', -90, ...
    'MaxRange', 15, ...
    'AzimuthLimits', [-45 45], ...
    'ActorProfiles', profiles);
sensors{5} = lidarPointCloudGenerator('SensorIndex', 5, ...
    'SensorLocation', [2.8 0.9], ...
    'Yaw', 90, ...
    'MaxRange', 5, ...
    'AzimuthLimits', [-45 45], ...
    'ActorProfiles', profiles);
sensors{6} = lidarPointCloudGenerator('SensorIndex', 6, ...
    'SensorLocation', [2.8 -0.9], ...
    'Yaw', -90, ...
    'MaxRange', 5, ...
    'AzimuthLimits', [-45 45], ...
    'ActorProfiles', profiles);
sensors{7} = lidarPointCloudGenerator('SensorIndex', 7, ...
    'SensorLocation', [2.8 0.9], ...
    'Yaw', 90, ...
    'MaxRange', 15, ...
    'AzimuthLimits', [-45 45], ...
    'ActorProfiles', profiles);
sensors{8} = drivingRadarDataGenerator('SensorIndex', 8, ...
    'MountingLocation', [2.8 0.9 0.2], ...
    'MountingAngles', [36.1581854398083 0 0], ...
    'RangeLimits', [0 24], ...
    'TargetReportFormat', 'Detections', ...
    'ReferenceRange', 24, ...
    'FieldOfView', [90 5], ...
    'Profiles', profiles);
sensors{9} = drivingRadarDataGenerator('SensorIndex', 9, ...
    'MountingLocation', [2.8 -0.9 0.2], ...
    'MountingAngles', [-42.6088182166764 0 0], ...
    'RangeLimits', [0 24], ...
    'TargetReportFormat', 'Detections', ...
    'FieldOfView', [90 5], ...
    'Profiles', profiles);
sensors{10} = drivingRadarDataGenerator('SensorIndex', 10, ...
    'MountingLocation', [0 0.9 0.2], ...
    'MountingAngles', [150.945395900923 0 0], ...
    'RangeLimits', [0 12], ...
    'TargetReportFormat', 'Detections', ...
    'FieldOfView', [90 5], ...
    'Profiles', profiles);
sensors{11} = drivingRadarDataGenerator('SensorIndex', 11, ...
    'MountingLocation', [0 -0.9 0.2], ...
    'MountingAngles', [-150.294687605271 0 0], ...
    'RangeLimits', [0 12], ...
    'TargetReportFormat', 'Detections', ...
    'FieldOfView', [90 5], ...
    'Profiles', profiles);
numSensors = 11;

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = drivingScenario('StopTime', 10);

% Add all road segments
roadCenters = [200.6 129.7 0;
    18.1 3.9 0;
    -213.1 423.2 0];
laneSpecification = lanespec(2, 'Width', 7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

roadCenters = [152.7 189.7 0;
    14.7 -14.15 0;
    168.9 -102.8 0];
laneSpecification = lanespec(2, 'Width', 7);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road1');

roadCenters = [-124.8 472.4 0;
    143.3 -122.4 0];
marking = [laneMarking('Dashed', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Width', 7.425, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road2');

roadCenters = [125.5 -73.6 0;
    217 30.1 0;
    37.2 215.8 0;
    -85.2 389.1 0;
    -262 224 0;
    -275.6 123.9 0;
    -239.8 -103 0;
    -80 -126.2 0;
    75.3 -76.9 0];
marking = [laneMarking('Dashed', 'Color', [0.98 0.86 0.36])
    laneMarking('Dashed')
    laneMarking('Solid')];
laneSpecification = lanespec(2, 'Width', 4.925, 'Marking', marking);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road3');

roadCenters = [78 432 0;
    -355 104 0];
laneSpecification = lanespec(2, 'Width', 7.425);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road4');

roadCenters = [139 262 0;
    -417 -156 0];
laneSpecification = lanespec(2, 'Width', 7.425);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road5');

roadCenters = [285.7 -61.4 0;
    97 35 0];
laneSpecification = lanespec(2, 'Width', 7.425);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road6');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-217.5 419.8 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.85 0.325 0.098], ...
    'Name', 'EgoCar');
waypoints = [-217.6 415.5 0;
    -218.9 396.6 0;
    -221.2 327.3 0;
    -220.8 283.8 0;
    -213.4 224.7 0;
    -201.5 169.8 0;
    -182.3 123.4 0;
    -158.9 83.4 0;
    -122.4 47.3 0;
    -83 20.2 0;
    -46.5 4.40000000000001 0;
    -13.1 -0.799999999999997 0;
    7.19999999999999 -3.59999999999999 0;
    12 -14.7 0;
    32.8 -47.2 0;
    57 -67.8 0;
    73.9 -80.3 0;
    105.9 -91.1 0;
    128.7 -84 0;
    129.2 -77 0;
    140.7 -67.5 0;
    159.6 -55.8 0;
    193.7 -25.9 0;
    203.1 -13.1 0;
    215.7 10.5 0;
    219.4 45.8 0;
    207 86.2 0;
    163.8 130.4 0;
    132.5 151.7 0;
    103.2 162.9 0;
    79.7 149.6 0;
    47.5 122.1 0;
    42.1 118.1 0;
    35.4 125.6 0;
    22.1 157.3 0;
    3.5 197.5 0;
    -13.5 232.8 0;
    -25.4 261.1 0;
    -45.1 305.8 0;
    -68.7 357.7 0;
    -78.1 379.3 0;
    -84.9 392.4 0;
    -98.5 396.2 0;
    -121.7 398.3 0;
    -148.5 394.7 0;
    -178 380.6 0;
    -196.8 367.7 0;
    -212.9 351.2 0;
    -228.2 330.2 0;
    -243.5 301.4 0;
    -255.1 266.9 0;
    -264 229.4 0;
    -271.1 174.8 0;
    -280.6 114 0;
    -288.8 28.8 0;
    -260.3 -84.4 0;
    -235.4 -110.8 0];
speed = [90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90;90];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
car2 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-217.775581353059 386.914437115267 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [0.301 0.745 0.933], ...
    'Name', 'Car2');
waypoints = [-217.775581353059 386.914437115267 0;
    -218.3 367.8 0;
    -219.2 335.2 0;
    -218.9 316.2 0;
    -219.2 298.3 0;
    -218.5 281.7 0;
    -214.7 241.9 0;
    -208.9 217.5 0];
speed = [30;30;30;30;30;30;30;30];
trajectory(car2, waypoints, speed);

car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-234.115744145659 308.823516213237 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'PlotColor', [255 255 0] / 255, ...
    'Name', 'Car1');
waypoints = [-234.115744145659 308.823516213237 0;
    -224.8 324.9 0;
    -212.9 342.4 0;
    -203.2 355.4 0;
    -191.6 364.8 0;
    -178.1 375.8 0];
speed = [50;50;50;50;50;50];
trajectory(car1, waypoints, speed);

bicycle = actor(scenario, ...
    'ClassID', 3, ...
    'Length', 1.7, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [-223.7 321.5 0], ...
    'Mesh', driving.scenario.bicycleMesh, ...
    'PlotColor', [255 0 255] / 255, ...
    'Name', 'Bicycle');
waypoints = [-223.7 321.5 0;
    -223.7 312.1 0;
    -223.3 290.4 0;
    -222.4 267.2 0;
    -221.2 256.6 0;
    -220 251 0];
speed = [10;10;10;10;10;10];
trajectory(bicycle, waypoints, speed);

function output = getDetectorOutput(sensor)

if isa(sensor, 'visionDetectionGenerator')
    output = sensor.DetectorOutput;
elseif isa(sensor, 'lidarPointCloudGenerator')
    output = 'PointCloud';
elseif isa(sensor, 'insSensor')
    output = 'INSMeasurement';
else
    output = 'Objects only';
end

